import { useState } from "react";
import { AnalysisResult, CICDPlatform, CICDConfig, TestFramework, ProjectType } from "../types";

interface CICDPanelProps {
  analysis: AnalysisResult;
  framework: TestFramework;
}

const PLATFORM_META: Record<CICDPlatform, { icon: string; label: string; color: string; accent: string }> = {
  github:  { icon: "🐙", label: "GitHub Actions",  color: "bg-[#6e40c9]/5 border-[#6e40c9]/20",  accent: "#6e40c9" },
  gitlab:  { icon: "🦊", label: "GitLab CI",        color: "bg-[#fc6d26]/5 border-[#fc6d26]/20",  accent: "#fc6d26" },
  jenkins: { icon: "🏗️",  label: "Jenkins Pipeline", color: "bg-[#d33833]/5 border-[#d33833]/20",  accent: "#d33833" },
};

// Map project+framework to install/test commands
function getCommands(projectType: ProjectType, framework: TestFramework) {
  if (projectType === "python") return {
    install: "pip install -r requirements.txt",
    test: "pytest --cov=. --cov-report=xml --cov-report=term",
    lint: "flake8 . && black --check .",
    runtime: "python",
    runtimeVersion: "3.11",
    cacheKey: "pip-${{ hashFiles('requirements.txt') }}",
    cachePath: "~/.cache/pip",
    setupStep: "pip install pytest pytest-cov flake8 black",
    artifact: "coverage.xml",
  };
  if (projectType === "java") return {
    install: "mvn install -DskipTests",
    test: "mvn test",
    lint: "mvn checkstyle:check",
    runtime: "java",
    runtimeVersion: "17",
    cacheKey: "maven-${{ hashFiles('**/pom.xml') }}",
    cachePath: "~/.m2",
    setupStep: "",
    artifact: "target/surefire-reports/**/*.xml",
  };
  // JS/TS
  const testCmd = framework === "jest" ? "jest --coverage --ci"
    : framework === "vitest" ? "vitest run --coverage"
    : framework === "mocha" ? "mocha --reporter spec"
    : "jest --coverage --ci";
  return {
    install: "npm ci",
    test: `npx ${testCmd}`,
    lint: "npm run lint",
    runtime: "node",
    runtimeVersion: "20",
    cacheKey: "node-${{ hashFiles('package-lock.json') }}",
    cachePath: "~/.npm",
    setupStep: "",
    artifact: "coverage/lcov.info",
  };
}

function buildGithubActions(analysis: AnalysisResult, framework: TestFramework): CICDConfig {
  const cmd = getCommands(analysis.projectType, framework);
  const isJava = analysis.projectType === "java";
  const isPy = analysis.projectType === "python";

  const setupRuntime = isJava
    ? `      - name: Set up JDK ${cmd.runtimeVersion}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '${cmd.runtimeVersion}'`
    : isPy
    ? `      - name: Set up Python ${cmd.runtimeVersion}
        uses: actions/setup-python@v5
        with:
          python-version: '${cmd.runtimeVersion}'`
    : `      - name: Set up Node.js ${cmd.runtimeVersion}
        uses: actions/setup-node@v4
        with:
          node-version: '${cmd.runtimeVersion}'
          cache: 'npm'`;

  const setupStep = cmd.setupStep
    ? `\n      - name: Install test dependencies\n        run: ${cmd.setupStep}\n` : "";

  const coverageUpload = isPy
    ? `\n      - name: Upload coverage to Codecov\n        uses: codecov/codecov-action@v4\n        with:\n          file: ${cmd.artifact}\n          fail_ci_if_error: false\n`
    : isJava ? ""
    : `\n      - name: Upload coverage\n        uses: codecov/codecov-action@v4\n        with:\n          file: ${cmd.artifact}\n          fail_ci_if_error: false\n`;

  const content = `# ${analysis.projectName} — GitHub Actions CI/CD
# Auto-generated by TestForge AI
# Place this file at: .github/workflows/ci.yml

name: CI

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master]

env:
  NODE_ENV: test

jobs:
  test:
    name: Test & Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

${setupRuntime}

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${cmd.cachePath}
          key: \${{ runner.os }}-${cmd.cacheKey}
          restore-keys: \${{ runner.os }}-${cmd.runtime}-
${setupStep}
      - name: Install dependencies
        run: ${cmd.install}

      - name: Run linter
        run: ${cmd.lint}
        continue-on-error: true

      - name: Run tests
        run: ${cmd.test}
${coverageUpload}
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: ${cmd.artifact}
          retention-days: 30

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v4
${setupRuntime}

      - name: Install dependencies
        run: ${cmd.install}

      - name: Build project
        run: ${isJava ? "mvn package -DskipTests" : isPy ? "echo 'No build step for Python'" : "npm run build"}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ${isJava ? "target/*.jar" : isPy ? "dist/" : "dist/"}
          retention-days: 7
`;

  return {
    platform: "github",
    filename: ".github/workflows/ci.yml",
    content,
    description: "Push/PR trigger on main & develop. Runs lint → test → build with caching.",
  };
}

function buildGitlabCI(analysis: AnalysisResult, framework: TestFramework): CICDConfig {
  const cmd = getCommands(analysis.projectType, framework);
  const isJava = analysis.projectType === "java";
  const isPy = analysis.projectType === "python";
  const image = isJava ? `maven:3.9-eclipse-temurin-${cmd.runtimeVersion}`
    : isPy ? `python:${cmd.runtimeVersion}-slim`
    : `node:${cmd.runtimeVersion}-alpine`;

  const content = `# ${analysis.projectName} — GitLab CI/CD
# Auto-generated by TestForge AI
# Place this file at: .gitlab-ci.yml

image: ${image}

stages:
  - install
  - lint
  - test
  - build

variables:
  ${isPy ? "PIP_CACHE_DIR: \"$CI_PROJECT_DIR/.cache/pip\"" : isJava ? "MAVEN_OPTS: \"-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository\"" : "NPM_CACHE: \"$CI_PROJECT_DIR/.npm\""}

cache:
  paths:
    - ${cmd.cachePath.replace("~/", "")}

install:
  stage: install
  script:
    - ${cmd.setupStep ? cmd.setupStep + "\n    - " : ""}${cmd.install}
  artifacts:
    paths:
      - ${isJava ? ".m2/" : isPy ? ".cache/pip" : "node_modules/"}
    expire_in: 1 hour

lint:
  stage: lint
  script:
    - ${cmd.lint}
  allow_failure: true
  needs: [install]

test:
  stage: test
  script:
    - ${cmd.test}
  coverage: '/TOTAL.*\s+(\d+%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: ${isPy ? "coverage.xml" : isJava ? "target/site/jacoco/jacoco.xml" : "coverage/cobertura-coverage.xml"}
      junit:
        - ${isPy ? "junit.xml" : isJava ? "target/surefire-reports/TEST-*.xml" : "junit.xml"}
    expire_in: 1 week
  needs: [install]

build:
  stage: build
  script:
    - ${isJava ? "mvn package -DskipTests" : isPy ? "echo 'Build step not required for Python'" : "npm run build"}
  artifacts:
    paths:
      - ${isJava ? "target/*.jar" : "dist/"}
    expire_in: 1 week
  needs: [test]
  only:
    - main
    - master
`;

  return {
    platform: "gitlab",
    filename: ".gitlab-ci.yml",
    content,
    description: "4-stage pipeline: install → lint → test with coverage report → build.",
  };
}

function buildJenkins(analysis: AnalysisResult, framework: TestFramework): CICDConfig {
  const cmd = getCommands(analysis.projectType, framework);
  const isJava = analysis.projectType === "java";
  const isPy = analysis.projectType === "python";

  const content = `// ${analysis.projectName} — Jenkins Pipeline
// Auto-generated by TestForge AI
// Place this file at: Jenkinsfile (project root)

pipeline {
    agent any

    ${isJava ? `tools {
        jdk 'JDK-${cmd.runtimeVersion}'
        maven 'Maven-3.9'
    }` : ""}

    environment {
        ${isPy ? "PYTHONPATH = \"${WORKSPACE}\"" : isJava ? "JAVA_OPTS = '-Xmx512m'" : "NODE_ENV = 'test'"}
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
                echo "Building branch: ${"{"}BRANCH_NAME{"}"}"
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '${cmd.setupStep ? cmd.setupStep + " && " : ""}${cmd.install}'
            }
        }

        stage('Lint') {
            steps {
                sh '${cmd.lint}'
            }
            post {
                failure {
                    echo 'Lint failed — continuing anyway'
                }
            }
        }

        stage('Test') {
            steps {
                sh '${cmd.test}'
            }
            post {
                always {
                    ${isJava
                      ? `junit 'target/surefire-reports/**/*.xml'
                    jacoco(execPattern: 'target/*.exec')`
                      : isPy
                      ? `junit allowEmptyResults: true, testResults: 'junit.xml'
                    publishHTML target: [
                        reportDir: 'htmlcov',
                        reportFiles: 'index.html',
                        reportName: 'Coverage Report'
                    ]`
                      : `publishHTML target: [
                        reportDir: 'coverage/lcov-report',
                        reportFiles: 'index.html',
                        reportName: 'Coverage Report'
                    ]`
                    }
                }
            }
        }

        stage('Build') {
            when {
                anyOf {
                    branch 'main'
                    branch 'master'
                }
            }
            steps {
                sh '${isJava ? "mvn package -DskipTests" : isPy ? "echo 'No build step'" : "npm run build"}'
            }
            post {
                success {
                    archiveArtifacts artifacts: '${isJava ? "target/*.jar" : "dist/**"}',
                                     fingerprint: true
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        success {
            echo '✅ Pipeline completed successfully'
        }
        failure {
            echo '❌ Pipeline failed'
            // Uncomment to add Slack/email notifications:
            // slackSend channel: '#builds', color: 'danger', message: "FAILED: ${"{"}JOB_NAME{"}"} #${"{"}BUILD_NUMBER{"}"}"
        }
    }
}
`;

  return {
    platform: "jenkins",
    filename: "Jenkinsfile",
    content,
    description: "Declarative pipeline with checkout → install → lint → test → build stages.",
  };
}

export function CICDPanel({ analysis, framework }: CICDPanelProps) {
  const [platform, setPlatform] = useState<CICDPlatform>("github");
  const [copied, setCopied] = useState(false);

  const configs: Record<CICDPlatform, CICDConfig> = {
    github: buildGithubActions(analysis, framework),
    gitlab: buildGitlabCI(analysis, framework),
    jenkins: buildJenkins(analysis, framework),
  };

  const config = configs[platform];

  const handleCopy = () => {
    navigator.clipboard.writeText(config.content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([config.content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = config.filename.split("/").pop() ?? "ci-config.yml";
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-5">
      <div className="flex flex-wrap items-center justify-between gap-4">
        <div>
          <h3 className="text-white font-semibold text-sm tracking-wide">CI/CD Config Generator</h3>
          <p className="text-white/30 text-xs mt-0.5">
            Ready-to-use pipeline configs for {analysis.projectName} • {framework} test runner
          </p>
        </div>
        <div className="flex gap-2">
          <button
            onClick={handleCopy}
            className="px-3 py-1.5 text-xs text-white/60 hover:text-white border border-white/10 hover:border-white/30 rounded-lg transition-all flex items-center gap-1.5"
          >
            {copied ? <><span className="text-[#00ff9d]">✓</span> Copied!</> : <>📋 Copy</>}
          </button>
          <button
            onClick={handleDownload}
            className="px-3 py-1.5 text-xs bg-[#00ff9d] text-black font-bold rounded-lg hover:bg-[#00ff9d]/90 transition-all flex items-center gap-1.5"
          >
            ⬇ Download
          </button>
        </div>
      </div>

      {/* Platform selector */}
      <div className="grid grid-cols-3 gap-3">
        {(Object.keys(PLATFORM_META) as CICDPlatform[]).map(p => {
          const meta = PLATFORM_META[p];
          const cfg = configs[p];
          return (
            <button
              key={p}
              onClick={() => setPlatform(p)}
              className={`p-4 rounded-xl border text-left transition-all ${meta.color} ${
                platform === p
                  ? "ring-1 ring-white/25 scale-[1.02]"
                  : "hover:border-white/20"
              }`}
            >
              <div className="flex items-center gap-2.5 mb-2">
                <span className="text-2xl">{meta.icon}</span>
                <span className={`text-sm font-medium ${platform === p ? "text-white" : "text-white/60"}`}>
                  {meta.label}
                </span>
              </div>
              <p className="text-white/25 text-[10px] leading-relaxed">{cfg.description}</p>
              <p className="text-white/20 text-[10px] mt-1.5 font-mono">{cfg.filename}</p>
            </button>
          );
        })}
      </div>

      {/* Config preview */}
      <div>
        <div className="flex items-center gap-3 px-4 py-2.5 bg-[#111118] border border-white/8 rounded-t-xl">
          <div className="flex gap-1.5">
            <div className="w-3 h-3 rounded-full bg-red-500/60" />
            <div className="w-3 h-3 rounded-full bg-yellow-500/60" />
            <div className="w-3 h-3 rounded-full bg-green-500/60" />
          </div>
          <span className="text-white/40 text-xs font-mono ml-2">{config.filename}</span>
          <div className="ml-auto flex items-center gap-2">
            <span
              className="text-[10px] px-2 py-0.5 rounded-full font-medium"
              style={{
                backgroundColor: `${PLATFORM_META[platform].accent}20`,
                color: PLATFORM_META[platform].accent,
              }}
            >
              {PLATFORM_META[platform].label}
            </span>
          </div>
        </div>
        <div className="bg-[#0d0d14] border border-t-0 border-white/8 rounded-b-xl overflow-auto max-h-[60vh]">
          <pre className="text-xs leading-relaxed p-6 font-mono text-white/70 whitespace-pre">
            {config.content}
          </pre>
        </div>
      </div>

      {/* Quick setup guide */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
        {platform === "github" && [
          { step: "1", text: "Create .github/workflows/ directory" },
          { step: "2", text: "Save file as ci.yml in that folder" },
          { step: "3", text: "Push to GitHub — workflow starts automatically" },
        ].map(s => (
          <div key={s.step} className="p-3 bg-white/[0.02] border border-white/8 rounded-xl flex gap-3">
            <span className="w-5 h-5 rounded-full bg-[#6e40c9]/30 text-[#6e40c9] text-[10px] flex items-center justify-center flex-shrink-0 font-bold">{s.step}</span>
            <p className="text-white/40 text-xs">{s.text}</p>
          </div>
        ))}
        {platform === "gitlab" && [
          { step: "1", text: "Place .gitlab-ci.yml at project root" },
          { step: "2", text: "Enable CI/CD in GitLab project settings" },
          { step: "3", text: "Push — pipeline triggers on every commit" },
        ].map(s => (
          <div key={s.step} className="p-3 bg-white/[0.02] border border-white/8 rounded-xl flex gap-3">
            <span className="w-5 h-5 rounded-full bg-[#fc6d26]/30 text-[#fc6d26] text-[10px] flex items-center justify-center flex-shrink-0 font-bold">{s.step}</span>
            <p className="text-white/40 text-xs">{s.text}</p>
          </div>
        ))}
        {platform === "jenkins" && [
          { step: "1", text: "Place Jenkinsfile at project root" },
          { step: "2", text: "Create Pipeline job in Jenkins → SCM" },
          { step: "3", text: "Configure webhook or poll SCM trigger" },
        ].map(s => (
          <div key={s.step} className="p-3 bg-white/[0.02] border border-white/8 rounded-xl flex gap-3">
            <span className="w-5 h-5 rounded-full bg-[#d33833]/30 text-[#d33833] text-[10px] flex items-center justify-center flex-shrink-0 font-bold">{s.step}</span>
            <p className="text-white/40 text-xs">{s.text}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
